---
title: "Untitled"
author: "Tor Fibiger"
date: "12/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Attach Packages

```{r}

library(tidyverse)
library(janitor)
library(effsize)

```

#read in mack_creek_vertebrates

```{r}
mack_creek <- read.csv("mack_creek_vertebrates (1).csv") %>% 
  janitor::clean_names()
```


```{r}
results_a_prep_1 <- mack_creek %>% 
  filter(species == "DITE", section == "CC") %>% 
  group_by(year) %>% 
  summarize(total_count = n())

results_a_prep_2 <- mack_creek %>% 
  filter(species == "DITE", section == "OG") %>% 
  group_by(year) %>% 
  summarize(total_count = n())

```

```{r}
ggplot(results_a_prep_1, aes(x = year, y = total_count)) +
  geom_line(color = "red") +
  geom_line(data = results_a_prep_2, aes(x = year, y = total_count), color = "dark green") +
  theme_minimal() +
  scale_x_continuous(expand = c(0,0),
                     limits = c(1993, 2018),
                     breaks = seq(1993, 2017, by = 2)) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0, 400),
                     breaks = seq(0, 500, by = 100)) +
  labs(title = "Annual Salamander Counts in Clear Cut and Old Growth Sections of Mack Creek", x = "Year", y = "Salamander Count") +
annotate(geom = "text",
           x = 2003,
           y = 100,
           label = "Clear Cut",
           color = "red",
           size = 8) +
  annotate(geom = "text",
           x = 1998,
           y = 250,
           label = "Old Growth",
           color = "dark green",
           size = 8)
  
```

#Results D

```{r}
results_d_prep <- mack_creek %>% 
  filter(species == "DITE", year == "2017") %>% 
  select(section, weight) %>% 
  mutate(new_section = case_when(
         section == "OG" ~ "Old Growth",
         section == "CC" ~ "Clear Cut"))

og_weight <- results_d_prep %>% 
  filter(section == "OG")

cc_weight <- results_d_prep %>% 
  filter(section == "CC")

# Calculate mean weights (old growth vs. clear cut)
mean_weight_cc <- mean(cc_weight$weight, na.rm = TRUE)
mean_weight_og <- mean(og_weight$weight, na.rm = TRUE)

# Calculate mean weight standard deviation (old growth vs. clear cut)
sd_weight_cc <- sd(cc_weight$weight, na.rm = TRUE)
sd_weight_og <- sd(og_weight$weight, na.rm = TRUE)

# Calculate sample size (old growth vs. clear cut)
sample_size_cc <- count(cc_weight, na.rm = TRUE)
sample_size_og <- count(og_weight, na.rm = TRUE)

ttest_og_weight <- og_weight %>% 
  pull(weight)

ttest_cc_weight <- cc_weight %>% 
  pull(weight)

t_test <- t.test(test_cc_weight, ttest_og_weight)

weight_effect_size <- cohen.d(ttest_cc_weight, ttest_og_weight, na.rm = TRUE)

ggplot(data = results_d_prep, aes(x = weight)) +
  geom_histogram(fill = "black") +
  facet_wrap(~new_section) +
  theme_minimal() +
  labs(title = "Salamander Weight by Location", x = "Salamander Weight (grams)", y = "Count")

```

vhghfjgug 
